"use client";

import Image from "next/image";
import { motion } from "framer-motion";
import { manufacturingSteps } from "@/data/manufacturingData";
import CTABanner from "@/components/shared/CTABanner";
import { IMAGES } from "@/constants/images";

function FadeIn({ children, delay = 0, className = "" }: { children: React.ReactNode; delay?: number; className?: string }) {
  return (
    <motion.div initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-60px" }} transition={{ duration: 0.5, delay }} className={className}>
      {children}
    </motion.div>
  );
}

// ─── Step Icons Map ───────────────────────────────────────────
const STEP_ICONS: Record<number, React.ReactNode> = {
  1: (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="w-3 h-3">
      <path d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z" /><polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  ),
  2: (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="w-3 h-3">
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>
  ),
  3: (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="w-3 h-3">
      <path d="M21 16V8a2 2 0 00-1-1.73l-7-4a2 2 0 00-2 0l-7 4A2 2 0 003 8v8a2 2 0 001 1.73l7 4a2 2 0 002 0l7-4A2 2 0 0021 16z" />
    </svg>
  ),
  4: (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="w-3 h-3">
      <rect x="1" y="3" width="15" height="13" /><polygon points="16 8 20 8 23 11 23 16 16 16 16 8" /><circle cx="5.5" cy="18.5" r="2.5" /><circle cx="18.5" cy="18.5" r="2.5" />
    </svg>
  ),
  5: (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="w-3 h-3">
      <path d="M12 2.69l5.66 5.66a8 8 0 11-11.31 0z" />
    </svg>
  ),
  6: (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="w-3 h-3">
      <circle cx="12" cy="12" r="3" /><path d="M19.07 4.93a10 10 0 010 14.14M4.93 4.93a10 10 0 000 14.14M12 2v2M12 20v2M2 12h2M20 12h2" />
    </svg>
  ),
  7: (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="w-3 h-3">
      <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5" />
    </svg>
  ),
  8: (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="w-3 h-3">
      <line x1="18" y1="20" x2="18" y2="10" /><line x1="12" y1="20" x2="12" y2="4" /><line x1="6" y1="20" x2="6" y2="14" /><line x1="2" y1="20" x2="22" y2="20" />
    </svg>
  ),
};

// ─── Detail Sections ──────────────────────────────────────────
const detailSections = [
  {
    title: "Recycling & Processing",
    content: "The enterprise employs established mechanical recycling methodologies to process its aggregated waste materials. To achieve high-quality output, the core processing infrastructure relies on a suite of specialized industrial machinery. This physical infrastructure includes industrial crushers, washers, dryers, and integrated quality-control equipment. During the material conversion phase, the facility leverages both hot-wash and cold-wash processing techniques. These dual washing processes are utilized to ensure the resulting output materials meet the necessary purity, hygiene, and quality standards required for subsequent downstream manufacturing applications.",
    image: IMAGES.OPERATIONS_RECYCLING,
    imageAlt: "Recycling and processing facility",
    imageLeft: true,
  },
  {
    title: "Products & Outputs",
    content: "The primary commercial output generated by Bismillah Plastic's mechanical recycling operation is high-quality recycled plastic flakes. Following the hot-wash and cold-wash processing stages, these refined plastic materials are supplied directly to downstream manufacturers. The recovered plastic flakes function as crucial feedstock in the secondary manufacturing of fibers, plastic pellets, and various upcycled products. By supplying these materials, Bismillah Plastic fulfills industrial demand across both domestic and international markets, reinforcing the commercial viability of recycled plastics.",
    image: IMAGES.OPERATIONS_PRODUCTS,
    imageAlt: "Recycled plastic flakes products",
    imageLeft: false,
  },
  {
    title: "Business & Operational Impact",
    content: (
      <div className="space-y-4">
        <p className="text-stone-600 leading-relaxed text-justify">
          Bismillah Plastic has structured its operations for significant processing scale, working in conjunction with iDEA TREE, which acts as the project's development consultant. The operation is formally designated under the internal project framework: <span className="font-medium text-brand">BIS-Community Collection-All-Mechanical Recycling-Dinajpur-Bangladesh.</span>
        </p>
        <p className="text-stone-600 leading-relaxed">
          The enterprise's projected processing capacity over a continuous five-year timeline highlights substantial throughput capabilities and an anticipated trajectory of operational scaling:
        </p>
        <div className="overflow-x-auto mt-4">
          <div className="border-2 border-brand rounded-sm overflow-hidden shadow-sm">
            <table className="w-full text-sm border-collapse">
              <thead>
                <tr className="bg-brand text-white">
                  <th className="px-4 py-3 text-left font-semibold">Operating Period</th>
                  <th className="px-4 py-3 text-left font-semibold">Estimated Processing Capacity</th>
                </tr>
              </thead>
              <tbody>
                {[
                  { year: "Year 1", capacity: "15,000 MT" },
                  { year: "Year 2", capacity: "17,000 MT" },
                  { year: "Year 3", capacity: "20,000 MT" },
                  { year: "Year 4", capacity: "20,000 MT" },
                  { year: "Year 5", capacity: "24,000 MT" },
                ].map((row, i) => (
                  <tr key={row.year} className={i % 2 === 0 ? "bg-stone-50" : "bg-white"}>
                    <td className={`px-4 py-3 font-medium text-stone-700 ${i !== 4 ? "border-b border-stone-200" : ""}`}>{row.year}</td>
                    <td className={`px-4 py-3 text-brand font-bold ${i !== 4 ? "border-b border-stone-200" : ""}`}>{row.capacity}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    ),
    image: IMAGES.OPERATIONS_BUSINESS_IMPACT,
    imageAlt: "Business operations and impact",
    imageLeft: true,
  },
  {
    title: "Environmental & Resource Contribution",
    content: "The organization's operations act as a direct and measurable intervention against the deficit in local waste management infrastructure within Dinajpur, where municipal capabilities have not kept pace with regional growth. By capturing and processing a wide spectrum of mixed plastics, Bismillah Plastic effectively intercepts waste that poses documented environmental risks to local land and water resources. The enterprise actively facilitates large-scale waste diversion and resource recovery. By converting collected post-consumer waste into reusable recycled materials, the project directly supports circular economy principles. This mechanical recycling process reduces the broader industrial reliance on virgin plastic feedstocks, thereby creating a sustainable and closed-loop pathway for recovered plastics to re-enter productive economic use.",
    image: IMAGES.OPERATIONS_ENVIRONMENTAL,
    imageAlt: "Environmental contribution and sustainability",
    imageLeft: false,
  },
];

interface ManufacturingPageContentProps {
  header?: { headline?: string; description?: string };
}

export default function ManufacturingPageContent({ header }: ManufacturingPageContentProps) {
  return (
    <>
      {/* Hero */}
      <section className="relative pt-28 sm:pt-32 md:pt-36 pb-16 sm:pb-20 min-h-[320px] sm:min-h-[380px] flex items-center bg-brand text-white overflow-hidden">
        <div className="absolute inset-0">
          <Image
            src={IMAGES.HERO_MANUFACTURING}
            alt="Business Operations"
            fill
            sizes="100vw"
            quality={85}
            className="object-cover"
          />
          <div className="absolute inset-0 bg-gradient-to-r from-brand/95 via-brand/90 to-brand/80" />
        </div>
        <div className="container-wide relative z-10 text-center max-w-3xl mx-auto">
          <div className="flex items-center justify-center gap-3 mb-4">
            <div className="h-px w-8 bg-emerald-400/80" />
            <span className="eyebrow text-emerald-300">The Process</span>
            <div className="h-px w-8 bg-emerald-400/80" />
          </div>
          <h1 className="font-serif fluid-h1 text-white font-bold leading-tight mb-4">
            {header?.headline || "Business Operations"}
          </h1>
          <p className="text-base sm:text-lg text-white/80 max-w-2xl mx-auto leading-relaxed">
            {header?.description || "A comprehensive look at how Bismillah Plastic manages its integrated value chain — from community-level waste collection to the delivery of high-quality recycled plastic materials."}
          </p>
        </div>
      </section>

      {/* Intro / How It Works */}
      <section className="section-padding bg-ivory">
        <div className="container-wide max-w-5xl">
          {/* Section Header */}
          <FadeIn>
            <div className="text-center mb-14">
              <div className="flex items-center justify-center gap-3 mb-3">
                <div className="h-px w-8 bg-emerald-500/60" />
                <span className="eyebrow text-brand/70 uppercase tracking-widest text-xs font-semibold">Business Operations</span>
                <div className="h-px w-8 bg-emerald-500/60" />
              </div>
              <h2 className="font-serif text-3xl sm:text-4xl text-brand font-bold leading-tight mb-5">
                How Our Business Operations Works
              </h2>
              <p className="text-stone-600 leading-relaxed max-w-3xl mx-auto text-base sm:text-lg text-justify sm:text-center">
                Bismillah Plastic manages a comprehensive and integrated value chain that spans the entire lifecycle of plastic recycling. The operational workflow is organized into a sequential pipeline that begins at the community level and concludes with the distribution of processed industrial materials. The core operational flow is structured as follows:
              </p>
            </div>
          </FadeIn>

          {/* Process Timeline */}
          <div className="relative">
            {/* Vertical Line */}
            <div className="absolute left-4 md:left-1/2 top-0 bottom-0 w-px bg-stone-300 md:-translate-x-1/2" />

            <div className="space-y-8 sm:space-y-12">
              {manufacturingSteps.map((step, i) => {
                const isEven = i % 2 === 0;
                return (
                  <FadeIn key={step.step} delay={i * 0.08}>
                    <div className={`relative flex items-start md:items-center ${isEven ? "md:flex-row" : "md:flex-row-reverse"}`}>
                      {/* Step Icon Circle (0.8x compact size) */}
                      <div className="absolute left-4 md:left-1/2 w-8 h-8 md:w-9 md:h-9 rounded-full bg-brand text-white flex items-center justify-center border-2 border-ivory -translate-x-1/2 mt-1 md:mt-0 z-10 shadow-sm">
                        {STEP_ICONS[step.step]}
                      </div>

                      {/* Content Card with reduced padding (~0.9x) and no step count */}
                      <div className={`flex-1 w-full pl-14 md:pl-0 ${isEven ? "md:pr-12" : "md:pl-12"}`}>
                        <div className="bg-white p-5 sm:p-6 rounded-sm border border-stone-200 shadow-sm hover:shadow-md hover:border-brand/20 transition-all duration-300">
                          <h3 className="font-serif text-lg sm:text-xl text-brand font-semibold mb-2">{step.title}</h3>
                          <p className="text-sm sm:text-base text-stone-600 leading-relaxed text-justify">{step.description}</p>
                        </div>
                      </div>

                      {/* Spacer for alternating layout on desktop */}
                      <div className="hidden md:block flex-1" />
                    </div>
                  </FadeIn>
                );
              })}
            </div>
          </div>
        </div>
      </section>

      {/* Detail Sections — alternating image left/right */}
      {detailSections.map((section, i) => (
        <section
          key={section.title}
          className={`section-padding ${i % 2 === 0 ? "bg-white" : "bg-stone-50"}`}
        >
          <div className="container-wide">
            <FadeIn>
              <div className={`flex flex-col ${section.imageLeft ? "lg:flex-row" : "lg:flex-row-reverse"} gap-10 lg:gap-16 items-center`}>
                {/* Image */}
                <div className="w-full lg:w-[45%] flex-shrink-0">
                  <div className="relative aspect-[4/3] rounded-sm overflow-hidden shadow-lg">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={section.image}
                      alt={section.imageAlt}
                      className="w-full h-full object-cover transition-transform duration-700 hover:scale-105"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-brand/20 via-transparent to-transparent" />
                  </div>
                </div>

                {/* Content */}
                <div className="w-full lg:w-[55%]">
                  <h2 className="font-serif text-2xl sm:text-3xl text-brand font-bold leading-tight mb-5">
                    {section.title}
                  </h2>
                  {typeof section.content === "string" ? (
                    <p className="text-stone-600 leading-relaxed text-justify text-[15px]">{section.content}</p>
                  ) : (
                    section.content
                  )}
                </div>
              </div>
            </FadeIn>
          </div>
        </section>
      ))}

      <CTABanner
        headline="Partner With Our Recycling Operations"
        description="Contact our team to discuss material supply requirements or collection partnership opportunities."
        buttonText="Contact Us"
      />
    </>
  );
}
